
export const ROLES = {
  OWNER: 'owner',
  ADMIN: 'admin',
  ORG_ADMIN: 'org_admin',
  SUPER_ADMIN: 'super_admin',
  SUPERVISOR: 'supervisor',
  MEMBER: 'member',
  VIEWER: 'viewer',
};

export const SUITE_PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  MANAGE_ORGANIZATION: 'MANAGE_ORGANIZATION',
  MANAGE_BILLING: 'MANAGE_BILLING',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  CREATE_PROJECTS: 'CREATE_PROJECTS',
  EDIT_PROJECTS: 'EDIT_PROJECTS',
  DELETE_PROJECTS: 'DELETE_PROJECTS',
  VIEW_PROJECTS: 'VIEW_PROJECTS',
  MANAGE_APP_ACCESS: 'MANAGE_APP_ACCESS',
};

export const HSE_PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  REPORT_INCIDENT: 'REPORT_INCIDENT',
  MANAGE_INCIDENTS: 'MANAGE_INCIDENTS',
  APPROVE_PERMITS: 'APPROVE_PERMITS',
  CREATE_PERMITS: 'CREATE_PERMITS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  CONDUCT_AUDITS: 'CONDUCT_AUDITS',
  VIEW_AUDITS: 'VIEW_AUDITS',
  MANAGE_TEAM: 'MANAGE_TEAM',
};

// Permissions Matrix for Suite
const SUITE_ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(SUITE_PERMISSIONS),
  [ROLES.OWNER]: Object.values(SUITE_PERMISSIONS),
  [ROLES.ORG_ADMIN]: Object.values(SUITE_PERMISSIONS),
  [ROLES.ADMIN]: [
    SUITE_PERMISSIONS.VIEW_DASHBOARD,
    SUITE_PERMISSIONS.MANAGE_USERS,
    SUITE_PERMISSIONS.VIEW_ANALYTICS,
    SUITE_PERMISSIONS.CREATE_PROJECTS,
    SUITE_PERMISSIONS.EDIT_PROJECTS,
    SUITE_PERMISSIONS.VIEW_PROJECTS,
  ],
  [ROLES.MEMBER]: [
    SUITE_PERMISSIONS.VIEW_DASHBOARD,
    SUITE_PERMISSIONS.CREATE_PROJECTS,
    SUITE_PERMISSIONS.EDIT_PROJECTS,
    SUITE_PERMISSIONS.VIEW_PROJECTS,
  ],
  [ROLES.VIEWER]: [
    SUITE_PERMISSIONS.VIEW_DASHBOARD,
    SUITE_PERMISSIONS.VIEW_PROJECTS,
  ],
};

// Permissions Matrix for HSE
const HSE_ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(HSE_PERMISSIONS),
  [ROLES.OWNER]: Object.values(HSE_PERMISSIONS),
  [ROLES.ORG_ADMIN]: Object.values(HSE_PERMISSIONS),
  [ROLES.ADMIN]: Object.values(HSE_PERMISSIONS), // Admin has full HSE access typically
  [ROLES.SUPERVISOR]: [
    HSE_PERMISSIONS.VIEW_DASHBOARD,
    HSE_PERMISSIONS.REPORT_INCIDENT,
    HSE_PERMISSIONS.MANAGE_INCIDENTS,
    HSE_PERMISSIONS.APPROVE_PERMITS,
    HSE_PERMISSIONS.CREATE_PERMITS,
    HSE_PERMISSIONS.VIEW_REPORTS,
    HSE_PERMISSIONS.CONDUCT_AUDITS,
    HSE_PERMISSIONS.VIEW_AUDITS,
    HSE_PERMISSIONS.MANAGE_TEAM,
  ],
  [ROLES.MEMBER]: [
    HSE_PERMISSIONS.VIEW_DASHBOARD,
    HSE_PERMISSIONS.REPORT_INCIDENT,
    HSE_PERMISSIONS.CREATE_PERMITS,
    HSE_PERMISSIONS.VIEW_REPORTS,
    HSE_PERMISSIONS.VIEW_AUDITS,
  ],
  [ROLES.VIEWER]: [
    HSE_PERMISSIONS.VIEW_DASHBOARD,
    HSE_PERMISSIONS.VIEW_REPORTS,
    HSE_PERMISSIONS.VIEW_AUDITS,
  ],
};

/**
 * Check if a role has a specific permission in a given context
 * @param {string} role - The user's role
 * @param {string} permission - The permission to check
 * @param {string} context - 'suite' or 'hse'
 * @returns {boolean}
 */
export const canAccess = (role, permission, context = 'suite') => {
  if (!role) return false;
  
  const matrix = context === 'hse' ? HSE_ROLE_PERMISSIONS : SUITE_ROLE_PERMISSIONS;
  const rolePermissions = matrix[role] || [];
  
  return rolePermissions.includes(permission);
};
