import React from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Download, FileText, Presentation, TrendingUp, TrendingDown, Minus, AlertTriangle } from 'lucide-react';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

import WaterfallChart from './charts/WaterfallChart';
import TornadoChart from './charts/TornadoChart';
import StackedCashflowChart from './charts/StackedCashflowChart';
import SpiderChart from './charts/SpiderChart';
import { HistogramChart, SCurveChart } from './charts/RiskCharts';

const ResultsPanel = ({ results }) => {
  const { metrics, cashflow, sensitivity, risk, scenarios } = results;

  const formatCurrency = (val) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: 'compact' }).format(val);
  const formatPct = (val) => `${val.toFixed(1)}%`;

  // --- Export Functions ---
  const exportExcel = () => {
      const wb = XLSX.utils.book_new();
      
      // 1. Summary Sheet
      const summaryData = [
          ['Metric', 'Value'],
          ['NPV @ 10%', metrics.npv],
          ['IRR', metrics.irr],
          ['Payback', metrics.payback],
          ['Max Exposure', metrics.maxExposure],
          ['Total Revenue', metrics.totalRevenue],
          ['Total CAPEX', metrics.totalCapex]
      ];
      const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
      XLSX.utils.book_append_sheet(wb, wsSummary, "Executive Summary");

      // 2. Cashflow Sheet
      const wsCashflow = XLSX.utils.json_to_sheet(cashflow);
      XLSX.utils.book_append_sheet(wb, wsCashflow, "Cashflow Model");

      // 3. Scenarios Sheet
      if(scenarios) {
           const scenData = [
               { Metric: 'NPV', Base: scenarios.Base.metrics.npv, Low: scenarios.Low.metrics.npv, High: scenarios.High.metrics.npv },
               { Metric: 'IRR', Base: scenarios.Base.metrics.irr, Low: scenarios.Low.metrics.irr, High: scenarios.High.metrics.irr }
           ];
           XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(scenData), "Scenario Analysis");
      }
      
      XLSX.writeFile(wb, "NPV_Scenario_Report_vFinal.xlsx");
  };

  const exportPDF = () => {
      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(18);
      doc.text("Economic Evaluation Summary", 14, 20);
      doc.setFontSize(11);
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 28);

      // KPI Table
      doc.autoTable({
          head: [['Metric', 'Value', 'Unit']],
          body: [
              ['Net Present Value (NPV)', formatCurrency(metrics.npv), '$'],
              ['Internal Rate of Return (IRR)', metrics.irr.toFixed(1), '%'],
              ['Payback Period', metrics.payback.toFixed(1), 'Years'],
              ['Total CAPEX', formatCurrency(metrics.totalCapex), '$']
          ],
          startY: 35,
          theme: 'grid'
      });

      // Cashflow Table Snippet
      doc.text("Annual Cashflow (First 10 Years)", 14, doc.lastAutoTable.finalY + 15);
      doc.autoTable({
          head: [['Year', 'Revenue', 'CAPEX', 'OPEX', 'NCF']],
          body: cashflow.slice(0, 10).map(c => [c.year, c.grossRevenue.toFixed(1), c.capex.toFixed(1), c.opex.toFixed(1), c.ncf.toFixed(1)]),
          startY: doc.lastAutoTable.finalY + 20
      });
      
      // Footer
      doc.setFontSize(8);
      doc.text("Generated by Petrolord Suite - Confidential", 14, 290);

      doc.save("Economic_Summary_Report.pdf");
  };

  const getKPICardColor = (metric, value) => {
      if (metric === 'NPV') return value > 0 ? 'text-green-400' : 'text-red-400';
      if (metric === 'IRR') return value > 15 ? 'text-green-400' : value > 10 ? 'text-amber-400' : 'text-red-400';
      return 'text-white';
  };

  return (
    <div className="h-full flex flex-col space-y-4 animate-in fade-in duration-500">
        
        {/* Tabs Navigation */}
        <Tabs defaultValue="dashboard" className="flex-1 flex flex-col overflow-hidden">
            <div className="flex justify-between items-center flex-wrap gap-2">
                <TabsList className="bg-slate-900 border border-slate-800">
                    <TabsTrigger value="dashboard">Dashboard</TabsTrigger>
                    <TabsTrigger value="cashflow">Cashflow</TabsTrigger>
                    <TabsTrigger value="scenarios">Scenarios</TabsTrigger>
                    <TabsTrigger value="sensitivity">Sensitivity</TabsTrigger>
                    <TabsTrigger value="risk">Risk</TabsTrigger>
                </TabsList>
                <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={exportExcel} className="h-8 border-slate-700 text-slate-300 hover:text-white hover:bg-slate-800">
                        <FileText className="w-3 h-3 mr-2" /> Excel
                    </Button>
                    <Button variant="outline" size="sm" onClick={exportPDF} className="h-8 border-slate-700 text-slate-300 hover:text-white hover:bg-slate-800">
                        <Download className="w-3 h-3 mr-2" /> PDF
                    </Button>
                    <Button variant="outline" size="sm" className="h-8 border-slate-700 text-slate-300 hover:text-white hover:bg-slate-800">
                        <Presentation className="w-3 h-3 mr-2" /> PPT
                    </Button>
                </div>
            </div>

            {/* 1. Dashboard Tab */}
            <TabsContent value="dashboard" className="flex-1 overflow-y-auto space-y-4 mt-4">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <Card className="bg-slate-900 border-slate-800 p-4">
                        <p className="text-xs text-slate-500 uppercase font-semibold">Net Present Value</p>
                        <p className={`text-2xl font-bold ${getKPICardColor('NPV', metrics.npv)}`}>{formatCurrency(metrics.npv)}</p>
                    </Card>
                    <Card className="bg-slate-900 border-slate-800 p-4">
                        <p className="text-xs text-slate-500 uppercase font-semibold">Internal Rate of Return</p>
                        <p className={`text-2xl font-bold ${getKPICardColor('IRR', metrics.irr)}`}>{formatPct(metrics.irr)}</p>
                    </Card>
                    <Card className="bg-slate-900 border-slate-800 p-4">
                        <p className="text-xs text-slate-500 uppercase font-semibold">Payback Period</p>
                        <p className="text-2xl font-bold text-blue-400">{metrics.payback.toFixed(1)} Years</p>
                    </Card>
                    <Card className="bg-slate-900 border-slate-800 p-4">
                        <p className="text-xs text-slate-500 uppercase font-semibold">Max Exposure</p>
                        <p className="text-2xl font-bold text-red-400">{formatCurrency(Math.abs(metrics.maxExposure))}</p>
                    </Card>
                </div>
                <Card className="bg-slate-900 border-slate-800 flex-1 min-h-[400px]">
                    <CardHeader><CardTitle className="text-sm text-slate-300">Value Erosion Waterfall</CardTitle></CardHeader>
                    <CardContent className="h-[350px]">
                        <WaterfallChart metrics={metrics} />
                    </CardContent>
                </Card>
            </TabsContent>

            {/* 2. Cashflow Tab */}
            <TabsContent value="cashflow" className="flex-1 overflow-y-auto space-y-4 mt-4">
                <Card className="bg-slate-900 border-slate-800 h-[350px]">
                    <CardHeader><CardTitle className="text-sm text-slate-300">Annual Cashflow Profile</CardTitle></CardHeader>
                    <CardContent className="h-[300px]">
                        <StackedCashflowChart data={cashflow} />
                    </CardContent>
                </Card>
                <Card className="bg-slate-900 border-slate-800 overflow-hidden">
                    <Table>
                        <TableHeader>
                            <TableRow className="border-b-slate-800 bg-slate-950">
                                <TableHead className="text-slate-300">Year</TableHead>
                                <TableHead className="text-right text-emerald-400">Gross Rev</TableHead>
                                <TableHead className="text-right text-slate-400">Royalty</TableHead>
                                <TableHead className="text-right text-amber-400">OPEX</TableHead>
                                <TableHead className="text-right text-blue-400">CAPEX</TableHead>
                                <TableHead className="text-right text-red-400">Tax</TableHead>
                                <TableHead className="text-right font-bold text-white">NCF</TableHead>
                                <TableHead className="text-right text-slate-500">Cum. NCF</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {cashflow.map((row, i) => (
                                <TableRow key={i} className="border-b-slate-800 hover:bg-slate-800/50">
                                    <TableCell className="font-mono text-xs text-slate-400">{row.year}</TableCell>
                                    <TableCell className="font-mono text-xs text-right text-emerald-400">{formatCurrency(row.grossRevenue * 1e6)}</TableCell>
                                    <TableCell className="font-mono text-xs text-right text-slate-400">-{formatCurrency(row.royalty * 1e6)}</TableCell>
                                    <TableCell className="font-mono text-xs text-right text-amber-400">-{formatCurrency(row.opex * 1e6)}</TableCell>
                                    <TableCell className="font-mono text-xs text-right text-blue-400">-{formatCurrency(row.capex * 1e6)}</TableCell>
                                    <TableCell className="font-mono text-xs text-right text-red-400">-{formatCurrency(row.tax * 1e6)}</TableCell>
                                    <TableCell className={`font-mono text-xs text-right font-bold ${row.ncf >= 0 ? 'text-white' : 'text-red-400'}`}>{formatCurrency(row.ncf * 1e6)}</TableCell>
                                    <TableCell className="font-mono text-xs text-right text-slate-500">{formatCurrency(row.cumulativeNCF * 1e6)}</TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </Card>
            </TabsContent>

            {/* 3. Scenarios Tab */}
            <TabsContent value="scenarios" className="flex-1 overflow-y-auto space-y-4 mt-4">
                {scenarios && (
                    <div className="grid grid-cols-1 lg:grid-cols-1 gap-4">
                        <Card className="bg-slate-900 border-slate-800">
                            <CardHeader><CardTitle className="text-sm text-slate-300">Scenario Comparison Matrix</CardTitle></CardHeader>
                            <CardContent>
                                <Table>
                                    <TableHeader>
                                        <TableRow className="border-b-slate-800">
                                            <TableHead className="text-slate-300">Metric</TableHead>
                                            <TableHead className="text-right text-slate-400">Low Case</TableHead>
                                            <TableHead className="text-right font-bold text-white bg-slate-800/50">Base Case</TableHead>
                                            <TableHead className="text-right text-slate-400">High Case</TableHead>
                                            <TableHead className="text-right text-slate-500">Delta (Base vs High)</TableHead>
                                        </TableRow>
                                    </TableHeader>
                                    <TableBody>
                                        {[
                                            { label: 'NPV ($MM)', key: 'npv', format: (v) => formatCurrency(v) },
                                            { label: 'IRR (%)', key: 'irr', format: (v) => formatPct(v) },
                                            { label: 'Payback (Yrs)', key: 'payback', format: (v) => v.toFixed(1) },
                                            { label: 'Max Exposure ($MM)', key: 'maxExposure', format: (v) => formatCurrency(Math.abs(v)) }
                                        ].map(m => (
                                            <TableRow key={m.key} className="border-b-slate-800">
                                                <TableCell className="font-medium text-slate-300">{m.label}</TableCell>
                                                <TableCell className="text-right font-mono text-slate-400">{m.format(scenarios.Low.metrics[m.key])}</TableCell>
                                                <TableCell className="text-right font-mono font-bold text-white bg-slate-800/50">{m.format(scenarios.Base.metrics[m.key])}</TableCell>
                                                <TableCell className="text-right font-mono text-slate-400">{m.format(scenarios.High.metrics[m.key])}</TableCell>
                                                <TableCell className="text-right font-mono">
                                                    {(() => {
                                                        const diff = scenarios.High.metrics[m.key] - scenarios.Base.metrics[m.key];
                                                        const color = m.key === 'payback' || m.key === 'maxExposure' ? (diff < 0 ? 'text-green-400' : 'text-red-400') : (diff > 0 ? 'text-green-400' : 'text-red-400');
                                                        return <span className={color}>{diff > 0 ? '+' : ''}{m.key === 'irr' ? diff.toFixed(1)+'%' : m.key === 'payback' ? diff.toFixed(1) : formatCurrency(diff)}</span>;
                                                    })()}
                                                </TableCell>
                                            </TableRow>
                                        ))}
                                    </TableBody>
                                </Table>
                            </CardContent>
                        </Card>
                    </div>
                )}
            </TabsContent>

            {/* 4. Sensitivity Tab */}
            <TabsContent value="sensitivity" className="flex-1 overflow-y-auto space-y-4 mt-4">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 h-[450px]">
                    <Card className="bg-slate-900 border-slate-800">
                        <CardHeader><CardTitle className="text-sm text-slate-300">Tornado Chart (NPV Impact)</CardTitle></CardHeader>
                        <CardContent className="h-[380px]">
                            {sensitivity && <TornadoChart data={sensitivity.map(s => ({ name: s.name, low: s.lowParamNPV, high: s.highParamNPV, base: s.baseNPV }))} />}
                        </CardContent>
                    </Card>
                    <Card className="bg-slate-900 border-slate-800">
                        <CardHeader><CardTitle className="text-sm text-slate-300">Spider Plot</CardTitle></CardHeader>
                        <CardContent className="h-[380px]">
                            {sensitivity && <SpiderChart sensitivityData={sensitivity} />}
                        </CardContent>
                    </Card>
                </div>
            </TabsContent>

            {/* 5. Risk Tab */}
            <TabsContent value="risk" className="flex-1 overflow-y-auto space-y-4 mt-4">
                <div className="grid grid-cols-4 gap-4 mb-2">
                    <Card className="bg-slate-900 border-slate-800 p-4 col-span-1">
                         <p className="text-xs text-slate-500 uppercase font-semibold">EMV (Expected Value)</p>
                         <p className="text-xl font-bold text-blue-400">{risk ? formatCurrency(risk.emv) : '-'}</p>
                    </Card>
                    <div className="col-span-3 grid grid-cols-3 gap-4">
                        <div className="bg-slate-800/50 p-4 rounded border border-slate-700 text-center">
                            <p className="text-xs text-slate-500">P90 (Conservative)</p>
                            <p className="text-lg font-bold text-white">{risk ? formatCurrency(risk.p90) : '-'}</p>
                        </div>
                        <div className="bg-slate-800/50 p-4 rounded border border-slate-700 text-center">
                            <p className="text-xs text-slate-500">P50 (Base)</p>
                            <p className="text-lg font-bold text-white">{risk ? formatCurrency(risk.p50) : '-'}</p>
                        </div>
                        <div className="bg-slate-800/50 p-4 rounded border border-slate-700 text-center">
                            <p className="text-xs text-slate-500">P10 (Optimistic)</p>
                            <p className="text-lg font-bold text-white">{risk ? formatCurrency(risk.p10) : '-'}</p>
                        </div>
                    </div>
                </div>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 h-[400px]">
                     <Card className="bg-slate-900 border-slate-800">
                        <CardHeader><CardTitle className="text-sm text-slate-300">NPV Distribution</CardTitle></CardHeader>
                        <CardContent className="h-[340px]">
                            {risk && <HistogramChart data={risk.histogram} p10={risk.p10} p50={risk.p50} p90={risk.p90} />}
                        </CardContent>
                    </Card>
                    <Card className="bg-slate-900 border-slate-800">
                        <CardHeader><CardTitle className="text-sm text-slate-300">Cumulative Probability (S-Curve)</CardTitle></CardHeader>
                        <CardContent className="h-[340px]">
                            {risk && <SCurveChart data={risk.cdf} />}
                        </CardContent>
                    </Card>
                </div>
            </TabsContent>
        </Tabs>
    </div>
  );
};

export default ResultsPanel;