
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generatePDFReport = async (data, options) => {
    const doc = new jsPDF();
    const { title, sections, author } = options;

    // Title Page
    doc.setFontSize(24);
    doc.setTextColor(0, 51, 102); // Dark Blue
    doc.text(title || "Pore Pressure & Fracture Gradient Report", 20, 40);
    
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`Generated by: ${author || 'Petrolord Analyst'}`, 20, 50);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 58);

    doc.setLineWidth(0.5);
    doc.line(20, 65, 190, 65);

    let yPos = 80;

    // Executive Summary
    if (sections.includes('summary')) {
        doc.setFontSize(16);
        doc.setTextColor(0);
        doc.text("1. Executive Summary", 20, yPos);
        yPos += 10;
        doc.setFontSize(10);
        doc.text("This report summarizes the pore pressure and fracture gradient analysis performed on the subject well. The model utilizes Eaton's method with calibrated exponent derived from offset well data.", 20, yPos, { maxWidth: 170 });
        yPos += 30;
    }

    // Methodology
    if (sections.includes('methodology')) {
        if (yPos > 250) { doc.addPage(); yPos = 20; }
        doc.setFontSize(16);
        doc.text("2. Methodology", 20, yPos);
        yPos += 10;
        doc.setFontSize(10);
        doc.text("Standard industry practices were followed, integrating seismic velocity data, density logs, and direct pressure measurements (RFT/MDT).", 20, yPos, { maxWidth: 170 });
        yPos += 30;
    }

    // Results Table (Mocking data integration)
    if (sections.includes('results')) {
        if (yPos > 200) { doc.addPage(); yPos = 20; }
        doc.setFontSize(16);
        doc.text("3. Key Results", 20, yPos);
        yPos += 10;

        // Simple table of markers/casing points
        const tableData = [
            ['Depth (ft)', 'PP (ppg)', 'FG (ppg)', 'Lithology'],
            ['3500', '9.2', '12.5', 'Sandstone'],
            ['8000', '10.5', '14.2', 'Shale'],
            ['12500', '12.1', '15.8', 'Limestone'],
            ['15000', '14.5', '17.2', 'High Pressure Zone']
        ];

        doc.autoTable({
            startY: yPos,
            head: [tableData[0]],
            body: tableData.slice(1),
            theme: 'striped',
            headStyles: { fillColor: [22, 163, 74] } // Emerald green
        });
        
        yPos = doc.lastAutoTable.finalY + 20;
    }

    // Conclusions
    if (sections.includes('conclusions')) {
        if (yPos > 250) { doc.addPage(); yPos = 20; }
        doc.setFontSize(16);
        doc.text("4. Conclusions & Recommendations", 20, yPos);
        yPos += 10;
        doc.setFontSize(10);
        doc.text("• Narrow drilling window identified between 12,500 ft and 13,000 ft.", 20, yPos);
        yPos += 6;
        doc.text("• Recommended mud weight contingency of 0.5 ppg.", 20, yPos);
        yPos += 6;
        doc.text("• Casing point selection optimized to mitigate kick risk.", 20, yPos);
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount} - Petrolord PP-FG Analyzer`, 105, 290, { align: 'center' });
    }

    return doc.output('blob');
};
