import React from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Calculator, DollarSign, TrendingUp, Activity, Clock } from 'lucide-react';

const metrics = [
  {
    id: 'npv',
    title: 'Net Present Value (NPV)',
    icon: DollarSign,
    simple: 'The total value of the project in today\'s money.',
    formula: 'Sum [ Cashflow / (1 + Discount Rate)^Time ]',
    interpretation: 'Positive is good. It means the project earns more than the cost of capital.',
    color: 'text-emerald-400'
  },
  {
    id: 'irr',
    title: 'Internal Rate of Return (IRR)',
    icon: TrendingUp,
    simple: 'The annual percentage return generated by the project.',
    formula: 'Discount rate where NPV = 0',
    interpretation: 'Higher is better. Compare this against your company\'s hurdle rate (usually 10-15%).',
    color: 'text-blue-400'
  },
  {
    id: 'dpi',
    title: 'Discounted Profit Index (DPI)',
    icon: Calculator,
    simple: 'Efficiency ratio: How much value is created per dollar invested.',
    formula: 'NPV / PV(Capex)',
    interpretation: 'DPI > 1.0 is excellent. DPI < 0 means value destruction.',
    color: 'text-purple-400'
  },
  {
    id: 'payback',
    title: 'Payback Period',
    icon: Clock,
    simple: 'How long it takes to recover the initial investment.',
    formula: 'Time when Cumulative Cashflow turns positive',
    interpretation: 'Shorter is usually better for liquidity and risk reduction.',
    color: 'text-amber-400'
  }
];

const ResultsExplainer = () => {
  return (
    <Card className="bg-slate-900 border-slate-800">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-white">
            <Activity className="w-5 h-5 text-blue-500" />
            Metric Explainer
        </CardTitle>
      </CardHeader>
      <CardContent>
        <Accordion type="single" collapsible className="w-full">
          {metrics.map((metric) => (
            <AccordionItem key={metric.id} value={metric.id} className="border-slate-800">
              <AccordionTrigger className="hover:no-underline group">
                <div className="flex items-center gap-3">
                    <div className={`p-2 rounded bg-slate-950 border border-slate-800 group-hover:border-slate-700 transition-colors`}>
                        <metric.icon className={`w-4 h-4 ${metric.color}`} />
                    </div>
                    <span className="text-slate-200 font-medium">{metric.title}</span>
                </div>
              </AccordionTrigger>
              <AccordionContent className="pt-2 pb-4 px-1">
                <div className="space-y-3 pl-11">
                    <div>
                        <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">What is it?</span>
                        <p className="text-sm text-slate-300 mt-1">{metric.simple}</p>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="bg-slate-950/50 p-3 rounded border border-slate-800">
                            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">Math</span>
                            <code className="text-xs font-mono text-blue-300">{metric.formula}</code>
                        </div>
                        <div className="bg-slate-950/50 p-3 rounded border border-slate-800">
                            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">Interpretation</span>
                            <p className="text-xs text-slate-400">{metric.interpretation}</p>
                        </div>
                    </div>
                </div>
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </CardContent>
    </Card>
  );
};

export default ResultsExplainer;