/**
 * FDP Export Service
 * Generates PDF/Report documents from FDP state using jsPDF.
 */
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatNumber } from '@/utils/fdp/formatting';

export class FDPExportService {
    static async generatePDF(state, meta) {
        const doc = new jsPDF();
        const title = state.meta?.name || "Field Development Plan";
        
        // Cover Page
        doc.setFontSize(24);
        doc.text(title, 105, 100, { align: "center" });
        
        doc.setFontSize(14);
        doc.text(`Version: ${meta.version}`, 105, 115, { align: "center" });
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 105, 125, { align: "center" });
        
        doc.setFontSize(10);
        doc.text("Generated by PetroLord FDP Accelerator", 105, 280, { align: "center" });

        // Executive Summary
        doc.addPage();
        doc.setFontSize(18);
        doc.text("1. Executive Summary", 14, 20);
        doc.setFontSize(11);
        doc.text([
            `This Field Development Plan for ${state.fieldData?.fieldName} outlines the strategy for commercializing the discovered resources.`,
            "",
            `Location: ${state.fieldData?.country}, ${state.fieldData?.region}`,
            `Asset Type: ${state.fieldData?.assetType}`,
            `Water Depth: ${state.fieldData?.waterDepth}m`
        ], 14, 30);

        // Key Metrics Table
        autoTable(doc, {
            startY: 60,
            head: [['Key Metric', 'Value', 'Unit']],
            body: [
                ['P50 Reserves', formatNumber(state.subsurface?.reserves?.p50), 'MMbbl'],
                ['Total CAPEX', formatCurrency(state.economics?.capex, 'USD'), 'MM$'],
                ['NPV @ 10%', formatCurrency(state.economics?.npv, 'USD'), 'MM$'],
                ['IRR', formatNumber(state.economics?.irr), '%'],
                ['First Oil', state.fieldData?.dates?.firstOil || 'TBD', 'Date'],
                ['Well Count', state.wells?.list?.length || 0, 'Wells'],
            ],
            theme: 'grid',
            headStyles: { fillColor: [22, 163, 74] } // Green-600
        });

        // Subsurface
        doc.addPage();
        doc.setFontSize(18);
        doc.text("2. Subsurface Overview", 14, 20);
        
        const reservoirs = state.subsurface?.reserves?.breakdown || [];
        if(reservoirs.length > 0) {
            doc.setFontSize(14);
            doc.text("Reserves Breakdown", 14, 30);
            autoTable(doc, {
                startY: 35,
                head: [['Reservoir', 'Fluid', 'P90', 'P50', 'P10', 'RF']],
                body: reservoirs.map(r => [r.name, r.fluid, r.p90, r.p50, r.p10, r.rf]),
            });
        }

        // Wells
        doc.addPage();
        doc.setFontSize(18);
        doc.text("3. Drilling & Wells", 14, 20);
        const wells = state.wells?.list || [];
        if(wells.length > 0) {
            autoTable(doc, {
                startY: 30,
                head: [['Name', 'Type', 'Trajectory', 'MD (ft)', 'Cost (MM$)']],
                body: wells.map(w => [w.name, w.type, w.trajectory, w.md, (w.cost/1e6).toFixed(1)]),
            });
        }

        // Costs
        doc.addPage();
        doc.setFontSize(18);
        doc.text("4. Cost & Economics", 14, 20);
        const costs = state.costs?.items || [];
        if(costs.length > 0) {
            autoTable(doc, {
                startY: 30,
                head: [['Item', 'Category', 'Type', 'Amount (MM$)']],
                body: costs.map(c => [c.name, c.category, c.type, c.amount]),
            });
        }

        // Risks
        doc.addPage();
        doc.setFontSize(18);
        doc.text("5. Risk Management", 14, 20);
        
        // Consolidate risks (from various sources roughly)
        const risks = state.risks || []; 
        const hseRisks = state.hseData?.hazards || [];
        const allRisks = [...risks, ...hseRisks];

        if(allRisks.length > 0) {
            autoTable(doc, {
                startY: 30,
                head: [['Risk / Hazard', 'Type', 'Score', 'Mitigation']],
                body: allRisks.slice(0, 20).map(r => [
                    r.name, 
                    r.type || 'General', 
                    (r.probability||0)*(r.impact||0), 
                    r.mitigation || r.mitigationStrategy || '-'
                ]),
            });
        }

        return doc;
    }
}