import jsPDF from 'jspdf';
import 'jspdf-autotable';

export class ReportGenerator {
    
    static async generateProbabilisticReport(projectName, results, unitSystem, chartImages = {}) {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;
        const pageHeight = doc.internal.pageSize.height;
        const margin = 20;
        
        // Helper for text centering
        const centerText = (text, y) => {
            const textWidth = doc.getStringUnitWidth(text) * doc.internal.getFontSize() / doc.internal.scaleFactor;
            const x = (pageWidth - textWidth) / 2;
            doc.text(text, x, y);
        };

        const addHeader = (pageNo) => {
            doc.setFillColor(15, 23, 42); // Slate 900
            doc.rect(0, 0, pageWidth, 30, 'F');
            
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(18);
            doc.setFont('helvetica', 'bold');
            doc.text("ReservoirCalc Pro", margin, 12);
            
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.text("Probabilistic Resource Report", margin, 20);
            
            doc.text(`Project: ${projectName}`, pageWidth - margin, 12, { align: 'right' });
            doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin, 20, { align: 'right' });
        };

        const addFooter = (pageNo, totalPages) => {
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Page ${pageNo} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
            doc.text("Generated by ReservoirCalc Pro", pageWidth - margin, pageHeight - 10, { align: 'right' });
        };

        // --- PAGE 1: EXECUTIVE SUMMARY ---
        addHeader(1);
        
        let yPos = 45;
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text("Executive Summary", margin, yPos);
        
        yPos += 10;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text("This report summarizes the probabilistic volumetric estimation results based on Monte Carlo simulation.", margin, yPos);
        doc.text(`Unit System: ${unitSystem.charAt(0).toUpperCase() + unitSystem.slice(1)}`, margin, yPos + 5);
        
        // KPI Cards Drawing manually
        yPos += 15;
        const stats = results.stats.stooip;
        const cardWidth = (pageWidth - (margin * 2) - 10) / 3; // 3 cards with 5mm gap
        const cardHeight = 30;

        // P90
        doc.setDrawColor(200, 200, 200);
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(margin, yPos, cardWidth, cardHeight, 2, 2, 'FD');
        doc.setFontSize(9);
        doc.setTextColor(100, 116, 139);
        doc.text("P90 (PROVEN)", margin + cardWidth/2, yPos + 10, { align: 'center' });
        doc.setFontSize(16);
        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'bold');
        doc.text(`${(stats.p90/1e6).toFixed(2)} MM`, margin + cardWidth/2, yPos + 22, { align: 'center' });

        // P50
        doc.setDrawColor(16, 185, 129);
        doc.setFillColor(236, 253, 245);
        doc.roundedRect(margin + cardWidth + 5, yPos, cardWidth, cardHeight, 2, 2, 'FD');
        doc.setFontSize(9);
        doc.setTextColor(5, 150, 105);
        doc.text("P50 (PROBABLE)", margin + cardWidth + 5 + cardWidth/2, yPos + 10, { align: 'center' });
        doc.setFontSize(16);
        doc.setTextColor(6, 95, 70);
        doc.text(`${(stats.p50/1e6).toFixed(2)} MM`, margin + cardWidth + 5 + cardWidth/2, yPos + 22, { align: 'center' });

        // P10
        doc.setDrawColor(200, 200, 200);
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(margin + (cardWidth * 2) + 10, yPos, cardWidth, cardHeight, 2, 2, 'FD');
        doc.setFontSize(9);
        doc.setTextColor(100, 116, 139);
        doc.text("P10 (POSSIBLE)", margin + (cardWidth*2) + 10 + cardWidth/2, yPos + 10, { align: 'center' });
        doc.setFontSize(16);
        doc.setTextColor(15, 23, 42);
        doc.text(`${(stats.p10/1e6).toFixed(2)} MM`, margin + (cardWidth*2) + 10 + cardWidth/2, yPos + 22, { align: 'center' });

        // Detailed Table
        yPos += 45;
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text("Statistical Breakdown", margin, yPos);
        
        yPos += 5;
        const tableData = [
            ["Metric", "Value", "Unit", "Description"],
            ["Mean", (stats.mean/1e6).toFixed(2), "MMstb", "Average expected volume"],
            ["Median (P50)", (stats.p50/1e6).toFixed(2), "MMstb", "Middle value of distribution"],
            ["Minimum", (stats.min/1e6).toFixed(2), "MMstb", "Lowest simulated outcome"],
            ["Maximum", (stats.max/1e6).toFixed(2), "MMstb", "Highest simulated outcome"],
            ["Standard Deviation", (stats.stdDev/1e6).toFixed(2), "MMstb", "Measure of spread/uncertainty"],
            ["Range (Max-Min)", ((stats.max - stats.min)/1e6).toFixed(2), "MMstb", "Total span of outcomes"],
            ["P90/P10 Ratio", (stats.p10 / stats.p90).toFixed(2), "-", "Uncertainty ratio"]
        ];

        doc.autoTable({
            startY: yPos,
            head: [tableData[0]],
            body: tableData.slice(1),
            theme: 'grid',
            headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: 'bold' },
            styles: { fontSize: 10, cellPadding: 4 },
            columnStyles: { 0: { fontStyle: 'bold', width: 40 }, 3: { fontStyle: 'italic', textColor: 100 } }
        });

        // Tornado Chart on Page 1 if fits, otherwise Page 2. 
        // Let's put it on Page 1 if there's room, else start page 2.
        // Usually chart images are large. Let's go to Page 2 for visual analysis.
        
        // --- PAGE 2: VISUAL ANALYSIS ---
        doc.addPage();
        addHeader(2);
        
        yPos = 45;
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text("Visual Analysis", margin, yPos);
        
        yPos += 10;
        
        // 1. Histogram
        if (chartImages.histogram) {
            doc.setFontSize(12);
            doc.text("Volume Distribution (Histogram)", margin, yPos);
            yPos += 5;
            // Aspect ratio calculation or fixed
            const imgHeight = 70;
            const imgWidth = 170;
            doc.addImage(chartImages.histogram, 'PNG', margin, yPos, imgWidth, imgHeight);
            yPos += imgHeight + 10;
        }

        // 2. CDF
        if (chartImages.cdf) {
            // Check if we need new page
            if (yPos + 80 > pageHeight) {
                doc.addPage();
                addHeader(3); // Assuming dynamic later
                yPos = 45;
            }
            
            doc.setFontSize(12);
            doc.text("Expectation Curve (CDF)", margin, yPos);
            yPos += 5;
            const imgHeight = 70;
            const imgWidth = 170;
            doc.addImage(chartImages.cdf, 'PNG', margin, yPos, imgWidth, imgHeight);
            yPos += imgHeight + 10;
        }

        // --- PAGE 3: SENSITIVITY (or continue if space) ---
        // Check space for Tornado
        if (yPos + 90 > pageHeight) {
            doc.addPage();
            addHeader(doc.internal.getNumberOfPages());
            yPos = 45;
        }

        if (chartImages.tornado) {
            doc.setFontSize(14);
            doc.text("Sensitivity Analysis", margin, yPos);
            yPos += 10;
            
            doc.setFontSize(10);
            doc.text("Tornado chart displaying the impact of each parameter on the mean STOOIP.", margin, yPos);
            yPos += 5;
            
            const imgHeight = 80;
            const imgWidth = 170;
            doc.addImage(chartImages.tornado, 'PNG', margin, yPos, imgWidth, imgHeight);
            yPos += imgHeight + 10;
        }

        // Add Footer to all pages
        const totalPages = doc.internal.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
            doc.setPage(i);
            addFooter(i, totalPages);
        }

        doc.save(`${projectName}_Probabilistic_Report.pdf`);
    }
}